server:
  port: 8002
  max-http-header-size: 4048576
spring:
  application:
    name: COMMENTS-SERVER
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
instance:
    preferIpAddress: true

      